### ISSUE TITLE
Italy

### ISSUE THREAD

**Issue by Veritaly** [corradio/electricitymap#330] opened 2017-01-28 08:31 UTC
Who is the 900MW constant power of geothermal powerplants? Total IT consumption at 9:00 am about 17GW. Its to low for Italy.

**Comment by corradio** [comment] 2017-01-28 08:52
Yes we are aware. This is a duplicate of https://github.com/corradio/electricitymap/issues/7. Let's use the other issue instead!

**Closed by corradio** 2017-01-28 08:52 UTC
