### ISSUE TITLE
Sun visualization

### ISSUE THREAD

**Issue by parisenbouteille** [corradio/electricitymap#108] opened 2016-10-26 12:08 UTC
Basic idea: display a new layer with sun exposure info.
- "quick win" solution: add a transparency/opacity layer that gives an idea of the time in the day
[http://gis.stackexchange.com/questions/17184/method-to-shade-or-overlay-a-raster-map-to-reflect-time-of-day-and-ambient-light](url)

- less accessible: map the real-time exposure, maybe from a weather API. A visualization idea could be a "hillshade"-like layer ?
[https://www.wunderground.com/weather/api/](url)

**Comment by corradio** [comment] 2016-10-26 15:04
Duplicate of #8 . Let's continue there.

**Closed by corradio** 2016-10-26 15:04 UTC
