### ISSUE TITLE
International arrows are going nuts

### ISSUE THREAD

**Issue by brunolajoie** [corradio/electricitymap#129] opened 2016-11-11 18:41 UTC
![capture](https://cloud.githubusercontent.com/assets/22095643/20226047/c4cdce54-a846-11e6-94cc-ec0a4acd5e1c.PNG)

**Comment by corradio** [comment] 2016-11-11 19:29
Was it solved by a page refresh? I can't reproduce it :(

**Comment by corradio** [comment] 2016-11-11 19:38
I pushed a fix. I hope it works. If it happens again please let me know everything you did (was the page opened for a long time? did you resize the screen?). Preferably leave the page opened and ping me on Slack :)

**Closed** 2016-11-11 19:37 UTC
