### ISSUE TITLE
Toggle to show aggregated data

### ISSUE THREAD

**Issue by AllanLRH** [corradio/electricitymap#177] opened 2016-12-15 22:56 UTC
Make a toggle to show aggregated (summed or averaged) data over a given period of time. Would be interesting especially in case of solar and wind.

**Comment by martindaniel4** [comment] 2016-12-16 01:48
@AllanLRH is it a duplicate of https://github.com/corradio/electricitymap/issues/83 ?

**Comment by AllanLRH** [comment] 2016-12-16 13:22
Almost, but I don't think it is exactly… #83 suggests a playback of previous dates, as well as being able to explore static views/snapshots of previous dates.

I suggest a static view of data averaged over several days, weeks or months. It doesn't necessarily have to be a user defined period, but could be pre-calculated values, such as three days, a week, a month, three months… while it's cool with a live preview of the situation, a view of the aggregated data is often more informative :)

Just a note: If you decide to implement the averaging, the fact that "the average of averages (weighted with the relative size of the dataset) is equal the the average of the whole dataset" might make server bookkeeping/calculations less resource heavy.

**Comment by corradio** [comment] 2016-12-24 00:57
Hi Allan,

Thanks for the idea. Will definitely keep it in mind for further versions. We don't really think the UI will support those kind of aggregates, but if we find something cleaver we'll let you know!

Olivier

**Closed by corradio** 2016-12-24 00:57 UTC
