### ISSUE TITLE
Costo €/MWh Italia

### ISSUE THREAD

**Issue by F041** [corradio/electricitymap#386] opened 2017-02-22 15:17 UTC
http://www.mercatoelettrico.org/it/

**Comment by corradio** [comment] 2017-02-23 13:57
Hi @F041,

I'm not fluent in Italian. Can you give some background?
Italy seems to have many different zones with different prices:
https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=23.02.2017+00:00|CET|DAY&biddingZone.values=CTY|10YIT-GRTN-----B!BZN|10Y1001A1001A699&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)
![image](https://cloud.githubusercontent.com/assets/1655848/23261819/68219c74-f9d8-11e6-8fbd-bf5dafa28ee1.png)

**Comment by F041** [comment] 2017-02-23 14:44
I think the chart includes an average

**Comment by corradio** [comment] 2017-02-23 14:52
OK then this issue is a duplicate of https://github.com/corradio/electricitymap/issues/347

**Closed by corradio** 2017-02-23 14:52 UTC
Labels: data
