### ISSUE TITLE
Add option to display country colors by absolute GHG emissions per capita

### ISSUE THREAD

**Issue by brunolajoie** [corradio/electricitymap#100] opened 2016-10-21 11:46 UTC
Would be a nice to have a button that one can click on the front page, which would switch country colors from GHG emission intensity to absolute GHG emissions. Color scale could be from white to red, not to confound with absolute emissions.

**Comment by corradio** [comment] 2016-10-26 15:19
What information do you get from absolute emissions? I feel like you can't compare to anything?
What about showing it per capita instead? That's comparable!

**Comment by corradio** [comment] 2016-11-09 20:42
@brunolajoie ?

**Comment by brunolajoie** [comment] 2016-11-10 09:57
I felt it was important to get a sense of the weight of each country compared to one another in terms of GHG emissions.  It's also equally nice to have it per capita, true. Those idea are both quick win that I tought were worth implementing.

**Comment by corradio** [comment] 2016-11-10 11:53
OK I'll think about how we can implement the GHG / capita. Actually I think it makes sense to do it when we'll do #47

**Comment by corradio** [comment] 2016-12-29 15:44
Duplicate of #169

**Closed by corradio** 2016-12-29 15:44 UTC
Labels: enhancement, idea
